// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhauzdcgkfacxhxnrgrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloYXV6ZGNna2ZhY3hoeG5yZ3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTQ3NDcsImV4cCI6MjA3NDE3MDc0N30.3_TUwCy2Gp8bwclmjmxB-2BQtWCNzvZYo7g7C27wPj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});